### ISSUE TITLE
node升级0.12后报错

### ISSUE THREAD

**Issue by richenlin** [zxdong262/canvas-captcha#2]
`Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/wwwroot/node/thinknode/node_modules/canvas-captcha/node_modules/canvas/lib/bindings.js:2:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
`

**Comment by zxdong262** [comment]
试过重新编译一遍没？node环境变化时，这类组件需要重新编译。
rm -rf node_modules
npm install
